new-pull-requests:
  project-board:
    name: 'Pipeline for QA'
    review-column-name: 'REVIEW'

  welcome-bot:
    message: 'Thanks for making your first PR here!'

bounty-awaiting-approval:
  project-board:
    name: 'Status SOB Swarm'
    approval-column-name: 'bounty-awaiting-approval'

slack:
  notification:
    room: 'status-hubot'