bounty-project-board:
  name: 'Status SOB Swarm'
  bounty-label-name: 'bounty'
  bounty-size-label-name-regex: 'bounty-([a-zA-Z0-9]+)'
  awaiting-approval-label-name: 'bounty-awaiting-approval'
  awaiting-approval-column-name: 'bounty-awaiting-approval'
  bounty-bug-label-name: 'bounty-bug'
  bounty-bug-column-name: 'bounty-bug'
  post-approved-bounties-to-slack-room: 'openbounty-riot'
  owner: 'andytudhope'

welcome-bot:
  message-template: 'Hey @{user}, thanks for making your first pull request in {repo-name}! :heart:'

slack:
  notification:
    room: 'status-probot'
